# Generated by Django 5.0.1 on 2024-01-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regStudent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='laststname',
            new_name='lastname',
        ),
    ]
