# Generated by Django 5.0.1 on 2024-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regStudent', '0004_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
